export const packagesData = [
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Journey to the sacred abode of Lord Shiva in the Himalayas. Experience the divine energy of one of the twelve Jyotirlingas. This pilgrimage is a transformative journey through snow-capped peaks and spiritual awakening.",
    "destination": "Kedarnath, Uttarakhand",
    "duration": "5 days",
    "id": "j90tf0v4ymtj3f4",
    "images": [],
    "itinerary": "Day 1: Arrival in Rishikesh - Welcome to the yoga capital, settle into your accommodation, evening Ganga Aarti ceremony, spiritual orientation. \nDay 2: Rishikesh to Kedarnath Base - Drive through scenic Himalayan valleys, arrive at Kedarnath base camp, acclimatization and evening meditation. \nDay 3: Sacred Trek to Kedarnath Temple - Begin the spiritual trek through pine forests, witness the majestic Kedarnath Temple nestled in the mountains, perform sacred rituals and darshan, experience divine energy. \nDay 4: Meditation and Spiritual Practices - Full day of meditation, yoga, and spiritual practices at the temple, connect with the divine presence of Lord Shiva, evening reflection. \nDay 5: Return Journey - Trek back to base camp, drive to Rishikesh, reflect on your spiritual transformation, departure",
    "price": 15999,
    "title": "Kedarnath Divine Journey",
    "updated": "2026-04-23 12:05:35.318Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Visit the sacred temple of Lord Vishnu nestled in the Himalayas. Badrinath is one of the four sacred Dhams, representing the ultimate destination of spiritual seekers. Immerse yourself in devotion and divine grace.",
    "destination": "Badrinath, Uttarakhand",
    "duration": "4 days",
    "id": "wyg6iky0ln2rb81",
    "images": [],
    "itinerary": "Day 1: Arrival in Haridwar - Welcome to the gateway of the gods, settle in, evening Ganga Aarti at Har Ki Pauri, spiritual immersion begins. \nDay 2: Haridwar to Badrinath - Scenic drive through Himalayan foothills, stop at Devprayag (confluence of rivers), arrive in Badrinath, evening temple visit. \nDay 3: Badrinath Darshan and Rituals - Early morning darshan at Badrinath Temple, sacred bath in Tapt Kund hot springs, perform rituals, experience the presence of Lord Vishnu, meditation. \nDay 4: Spiritual Reflection and Return - Morning meditation, visit nearby temples, begin return journey to Haridwar, carry the blessings home",
    "price": 14999,
    "title": "Badrinath Spiritual Sojourn",
    "updated": "2026-04-23 12:05:35.318Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Experience the divine energy of the holiest city on the banks of the Ganges. Varanasi is where the eternal and mortal worlds meet. Witness the sacred rituals and spiritual transformation that have captivated pilgrims for millennia.",
    "destination": "Varanasi, Uttar Pradesh",
    "duration": "3 days",
    "id": "476sc3xnoijo7lb",
    "images": [],
    "itinerary": "Day 1: Arrival and Ghat Exploration - Arrive in the holiest city, explore the sacred ghats of Varanasi, witness the spiritual energy of Mother Ganga, evening Aarti ceremony. \nDay 2: Aarti Ceremony and Temple Visits - Participate in the mesmerizing Ganga Aarti at Dashashwamedh Ghat, visit Kashi Vishwanath Temple, explore ancient temples, understand the spiritual significance of Varanasi. \nDay 3: Spiritual Practices and Departure - Morning yoga and meditation on the ghats, boat ride on the Ganges, final blessings, departure with spiritual awakening",
    "price": 9999,
    "title": "Varanasi Spiritual Awakening",
    "updated": "2026-04-23 12:05:35.319Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Walk in the footsteps of Lord Krishna in his birthplace. Mathura is the land of divine love and devotion. Experience the playful energy of Krishna and the eternal love of Radha-Krishna.",
    "destination": "Mathura, Uttar Pradesh",
    "duration": "3 days",
    "id": "phghcu8p5atfz8y",
    "images": [],
    "itinerary": "Day 1: Arrival and Krishna Temple Visits - Arrive in the birthplace of Lord Krishna, visit Krishna Janmabhoomi Temple, explore the sacred sites of Krishna's childhood, evening Aarti. \nDay 2: Vrindavan Exploration - Journey to Vrindavan, visit Banke Bihari Temple and Radha Raman Temple, experience the divine love of Radha-Krishna, participate in evening Aarti, immerse in devotional atmosphere. \nDay 3: Radha Krishna Temples and Departure - Visit Govind Dev Temple and other sacred temples, participate in morning prayers, reflect on Krishna's teachings, departure with divine blessings",
    "price": 10999,
    "title": "Mathura Krishna Pilgrimage",
    "updated": "2026-04-23 12:05:35.319Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Witness the grandeur of the newly constructed Ram Mandir. Ayodhya is the birthplace of Lord Rama, the embodiment of dharma and righteousness. This pilgrimage celebrates the triumph of good over evil.",
    "destination": "Ayodhya, Uttar Pradesh",
    "duration": "3 days",
    "id": "hqz6lsprsi98gjb",
    "images": [],
    "itinerary": "Day 1: Arrival and Ram Mandir Darshan - Arrive in Ayodhya, witness the grandeur of the newly constructed Ram Mandir, perform sacred rituals, experience the divine presence of Lord Rama. \nDay 2: Hanuman Garhi and Temple Exploration - Visit Hanuman Garhi Temple, explore Kanak Bhawan and other ancient temples, understand the significance of Ayodhya in Hindu mythology, evening prayers. \nDay 3: Spiritual Reflection and Departure - Morning meditation at Ram Mandir, participate in Aarti, carry the blessings of Lord Rama, departure with renewed faith",
    "price": 11999,
    "title": "Ayodhya Ram Mandir Journey",
    "updated": "2026-04-23 12:05:35.319Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Experience the spiritual sanctity of the Golden Temple. The Golden Temple is a beacon of hope, equality, and divine grace. Immerse yourself in the Sikh tradition of service and devotion.",
    "destination": "Amritsar, Punjab",
    "duration": "2 days",
    "id": "j4wqeww8k2q6wo0",
    "images": [],
    "itinerary": "Day 1: Arrival and Golden Temple Darshan - Arrive in Amritsar, visit the magnificent Golden Temple, experience the spiritual sanctity, participate in evening prayers, witness the divine glow of the temple. \nDay 2: Langar Experience and Departure - Participate in the sacred Langar (community meal), understand the philosophy of equality and service, visit Jallianwala Bagh, departure with blessings",
    "price": 8999,
    "title": "Amritsar Golden Temple Blessing",
    "updated": "2026-04-23 12:05:35.320Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Immerse yourself in the divine rituals on the banks of Mother Ganga. Haridwar is the gateway to the gods and the place where the Ganges descends to the plains. Witness the mesmerizing Ganga Aarti.",
    "destination": "Haridwar, Uttarakhand",
    "duration": "2 days",
    "id": "uz86ucw373qqyy8",
    "images": [],
    "itinerary": "Day 1: Arrival and Ganga Aarti - Arrive in Haridwar, settle in, witness the mesmerizing Ganga Aarti at Har Ki Pauri, experience the divine energy of Mother Ganga, evening meditation. \nDay 2: Temple Visits and Departure - Visit Mansa Devi Temple and Chandi Devi Temple, take a dip in the sacred Ganges, participate in morning prayers, departure with spiritual blessings",
    "price": 7999,
    "title": "Haridwar Ganga Aarti Experience",
    "updated": "2026-04-23 12:05:35.320Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Discover inner peace through yoga and meditation in the yoga capital of India. Rishikesh is where ancient wisdom meets modern wellness. Transform your body, mind, and spirit.",
    "destination": "Rishikesh, Uttarakhand",
    "duration": "4 days",
    "id": "fepczsm7x75wvt7",
    "images": [],
    "itinerary": "Day 1: Arrival and Orientation - Arrive in the yoga capital of India, settle in, evening orientation and introduction to yoga philosophy, Ganga Aarti ceremony. \nDay 2: Yoga and Meditation Sessions - Morning yoga practice, meditation sessions, learn ancient yogic techniques, evening Aarti and reflection. \nDay 3: Yoga and Spiritual Practices - Continued yoga and meditation, visit ashrams, understand the path of self-discovery, evening spiritual discourse. \nDay 4: Final Practice and Departure - Morning yoga session, meditation, carry the inner peace home, departure with spiritual transformation",
    "price": 12999,
    "title": "Rishikesh Yoga & Spirituality",
    "updated": "2026-04-23 12:05:35.320Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.204Z",
    "description": "Seek blessings at the sacred Mahakaleshwar Temple. Ujjain is one of the four sacred Dhams and home to the Kumbh Mela. Experience the mystical power of Lord Shiva.",
    "destination": "Ujjain, Madhya Pradesh",
    "duration": "3 days",
    "id": "5chu49x7wjnutg4",
    "images": [],
    "itinerary": "Day 1: Arrival and Mahakal Darshan - Arrive in Ujjain, visit the sacred Mahakaleshwar Temple, experience the divine presence of Lord Shiva, perform rituals, evening Aarti. \nDay 2: Hari Parbat and Temple Exploration - Visit Hari Parbat Temple, explore other sacred temples, understand the spiritual significance of Ujjain, participate in evening prayers. \nDay 3: Spiritual Reflection and Departure - Morning meditation at Mahakal Temple, participate in Aarti, carry the blessings of Lord Shiva, departure with divine grace",
    "price": 10999,
    "title": "Ujjain Mahakal Temple Journey",
    "updated": "2026-04-23 12:05:35.321Z"
  },
  {
    "collectionId": "pbc_9492306209",
    "collectionName": "packages",
    "created": "2026-04-23 10:19:24.205Z",
    "description": "Visit the legendary kingdom of Lord Krishna at the western edge of India. Dwarka is where Krishna established his divine kingdom. Experience the eternal love and divine play of Krishna.",
    "destination": "Dwarka, Gujarat",
    "duration": "4 days",
    "id": "bb9ag4mwz0ar7x8",
    "images": [],
    "itinerary": "Day 1: Arrival and Dwarkadhish Temple - enter Krishna's kingdom. \nDay 2: Nageshwar Temple and Bet Dwarka - explore sacred islands. \nDay 3: Spiritual practices - immerse in Krishna's energy. \nDay 4: Departure - blessed by Krishna's grace.",
    "price": 13999,
    "title": "Dwarka Krishna's Kingdom",
    "updated": "2026-04-23 10:19:24.205Z"
  }
];
